# Site settings
title: My Personal Website
email:
author: Thomas Lang
description:
url: bopas2.github.io

# Build settings
permalink: :title/
sass:
  sass_dir: css
theme: jekyll-theme-minimal

# Google Analytics
google_analytics: UA—167996569-1